.\" Process this file with
.\" groff -man -Tascii %FCN_NAME%.2
.\"
.TH %FCN_NAME% 1 "MARCH 2002" FramerD "FramerD API Documentation"
.SH NAME
%FCN_NAME% \- %SUMMARY%
.SH SYNOPSIS

.B %RET_TYPE% %FCN_NAME% (%FCN_ARGS%)

.SH Arguments
%ARG_INFO%
.SH Return value
%RET_INFO%
.SH Description
%DESCRIPTION%
.SH BUGS
No known bugs.
.SH AUTHOR
Ken Haase < kh@beingmeta.com >
.SH "SEE ALSO"
