#! /bin/sh
# postinst script for framerd
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.

case "$1" in
    (configure)
	/usr/sbin/framerd-setup /usr/share/framerd
	if [ -x /usr/bin/update-menus ]; then update-menus; fi
    ;;
    (upgrade)
	cp /etc/framerd.cfg /etc/framerd.cfg.bak
	/usr/sbin/framerd-setup /usr/share/framerd
    ;;

    (abort-upgrade|abort-remove|abort-deconfigure)
	cp /etc/framerd.cfg.bak  /etc/framerd.cfg
    ;;

    (*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


